title: Jonas Bird - writing portfolio
author: Jonas Bird
email: jonas.bird.m@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My professional writing samples - copy, technical, business, etc.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jonas-bird # DO NOT include the @ character, or else the build will fail!
mastadon_username:
show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-leap-day
